version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
     - net
    ports:
      - 80:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: flask
    networks:
      net:
        aliases:
          - fai
networks:
  net: